schema-version = 1

[package]
title = "Basic UI React Native Application for project localvideoasset"
version = "0.1.0"
id = "com.amazondeveloper.localvideoasset"

[[assets]]
source = "assets/"
destination = "assets/"

[components]
[[components.interactive]]
id = "com.amazondeveloper.localvideoasset.main"
runtime-module = "/com.amazon.kepler.keplerscript.runtime.loader_2@IKeplerScript_2_0"
launch-type = "singleton"
categories = ["com.amazon.category.main"]
