schema-version = 1

[package]
title = "Basic UI React Native Application for project localvideoasset"
version = "0.1.0"
id = "com.amazondeveloper.localvideoasset"

[[assets]]
source = "assets/"
destination = "assets/"

[components]
[[components.interactive]]
id = "com.amazondeveloper.localvideoasset.main"
runtime-module = "/com.amazon.kepler.keplerscript.runtime.loader_2@IKeplerScript_2_0"
launch-type = "singleton"
categories = ["com.amazon.category.main", "com.amazon.category.kepler.media"]

# Required for video playback
[[wants.service]]
id = "com.amazon.media.server"

# Required for emitting metrics from video playback
[[wants.service]]
id = "com.amazon.mediametrics.service"

# Required for video playback on stable APIs
[[wants.service]]
id = "com.amazon.mediabuffer.service"
[[wants.service]]
id = "com.amazon.mediatransform.service"

[[wants.service]]
 id = "com.amazon.gipc.uuid.*"

 [[wants.service]]
id = "com.amazon.media.playersession.service"

[[wants.service]]
 id = "com.amazon.audio.stream"

 [[wants.service]]
 id = "com.amazon.audio.control"

# Enable Group-IPC to access media services
[[wants.service]]
id = "com.amazon.gipc.uuid.*"